swagger: "2.0"
info:
  description: It is web server specification for the japan corona stats
  title: Japan Corona stats
  version: 1.0.0

paths:
  /coronaStats/{prefecture}:
    get:
      tags:
        - Prefecture wise
      summary: To get the stats prefecture wise
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: prefecture
          type: string
          required: true
          description: Prefecture name in Romaji
      security:
        - api_key: []
      responses:
        404:
          description: Prefecture not found
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/CoronaStatsPrefectureWise'

definitions:
  CoronaStatsPrefectureWise:
    type: object
    properties:
      tested:
        $ref: '#/definitions/Integer64'
      confirmed:
        $ref: '#/definitions/Integer64'
      recovered:
        $ref: '#/definitions/Integer64'
      active:
        $ref: '#/definitions/Integer64'
      critical:
        $ref: '#/definitions/Integer64'
      deaths:
        $ref: '#/definitions/Integer64'
  Integer64:
    type: integer
    format: int64

securityDefinitions:
  api_key:
    in: header
    type: apiKey
    name: api_key
